import { jsPDF } from "jspdf"

interface ShipmentData {
  bookingRef: string
  sapRef: string
  origin: string
  destination: string
  carrier: string
  vessel: string
  sailing: string
  containerType: string
  plant: string
  mode: string
}

const DEFAULT_DATA: ShipmentData = {
  bookingRef: "MAEU-2024-SHA-78432",
  sapRef: "SAP-TM-87234",
  origin: "Shanghai (CNSHA)",
  destination: "Los Angeles (USLAX)",
  carrier: "Maersk Line",
  vessel: "AE-1234 (Ever Given)",
  sailing: "Mar 22, 2024",
  containerType: "2×40' High Cube",
  plant: "Suzhou Plant",
  mode: "Ocean FCL",
}

function addHeader(doc: jsPDF, title: string) {
  // Blue header bar
  doc.setFillColor(30, 58, 95)
  doc.rect(0, 0, 210, 25, "F")
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(14)
  doc.setFont("helvetica", "bold")
  doc.text("Zero Touch Booking Agent", 15, 12)
  doc.setFontSize(9)
  doc.setFont("helvetica", "normal")
  doc.text("Automated Freight Documentation", 15, 18)

  // Document title
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(16)
  doc.setFont("helvetica", "bold")
  doc.text(title, 15, 38)

  // Divider line
  doc.setDrawColor(200, 200, 200)
  doc.line(15, 42, 195, 42)
}

function addField(doc: jsPDF, label: string, value: string, x: number, y: number) {
  doc.setTextColor(120, 120, 120)
  doc.setFontSize(8)
  doc.setFont("helvetica", "normal")
  doc.text(label, x, y)
  doc.setTextColor(30, 30, 30)
  doc.setFontSize(10)
  doc.setFont("helvetica", "bold")
  doc.text(value, x, y + 5)
}

function addFooter(doc: jsPDF, data: ShipmentData) {
  const y = 270
  doc.setDrawColor(200, 200, 200)
  doc.line(15, y, 195, y)
  doc.setTextColor(150, 150, 150)
  doc.setFontSize(7)
  doc.setFont("helvetica", "normal")
  doc.text(`Booking Ref: ${data.bookingRef}  |  SAP Ref: ${data.sapRef}  |  Generated by Zero Touch Booking Agent`, 15, y + 5)
  doc.text(`Generated: ${new Date().toLocaleDateString("en", { year: "numeric", month: "long", day: "numeric" })} ${new Date().toLocaleTimeString("en", { hour: "2-digit", minute: "2-digit" })}`, 15, y + 9)
}

export function generateSLI(data: ShipmentData = DEFAULT_DATA): void {
  const doc = new jsPDF()
  addHeader(doc, "Shipper's Letter of Instruction")

  let y = 50

  // Reference info
  doc.setFillColor(245, 247, 250)
  doc.rect(15, y, 180, 20, "F")
  addField(doc, "Booking Reference", data.bookingRef, 20, y + 6)
  addField(doc, "SAP Order Reference", data.sapRef, 100, y + 6)

  y += 28

  // Shipper / Consignee
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Shipper Information", 15, y)
  y += 8
  addField(doc, "Company", `${data.plant} — Electronics Division`, 15, y)
  addField(doc, "Address", "No. 88 Industrial Park, Suzhou, Jiangsu 215000, China", 100, y)
  y += 14
  addField(doc, "Contact", "Li Wei, Export Manager", 15, y)
  addField(doc, "Phone", "+86 512 6688 7799", 100, y)

  y += 18
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Consignee Information", 15, y)
  y += 8
  addField(doc, "Company", "Global Electronics Corp.", 15, y)
  addField(doc, "Address", "1200 Harbor Blvd, Los Angeles, CA 90012, USA", 100, y)

  y += 18
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Routing Instructions", 15, y)
  y += 8
  addField(doc, "Carrier", data.carrier, 15, y)
  addField(doc, "Vessel / Voyage", data.vessel, 100, y)
  y += 14
  addField(doc, "Port of Loading", data.origin, 15, y)
  addField(doc, "Port of Discharge", data.destination, 100, y)
  y += 14
  addField(doc, "Sailing Date", data.sailing, 15, y)
  addField(doc, "Container Type", data.containerType, 100, y)
  y += 14
  addField(doc, "Incoterm", "FOB Shanghai", 15, y)
  addField(doc, "Transport Mode", data.mode, 100, y)

  y += 18
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Description of Goods", 15, y)
  y += 8
  doc.setTextColor(30, 30, 30)
  doc.setFontSize(9)
  doc.setFont("helvetica", "normal")
  doc.text("Electronic components and laptop parts (HS 8471.30)", 15, y)
  doc.text("Gross Weight: 18,400 kg  |  Net Weight: 17,200 kg  |  Packages: 240 cartons", 15, y + 5)

  y += 20
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Special Instructions", 15, y)
  y += 7
  doc.setTextColor(80, 80, 80)
  doc.setFontSize(9)
  doc.setFont("helvetica", "normal")
  doc.text("1. Handle with care — fragile electronic components", 15, y)
  doc.text("2. Temperature-controlled storage not required", 15, y + 5)
  doc.text("3. Standard ocean freight — no hazardous materials", 15, y + 10)

  addFooter(doc, data)
  const blob = doc.output("blob")
  window.open(URL.createObjectURL(blob), "_blank")
}

export function generatePackingList(data: ShipmentData = DEFAULT_DATA): void {
  const doc = new jsPDF()
  addHeader(doc, "Commercial Packing List")

  let y = 50

  // Reference
  doc.setFillColor(245, 247, 250)
  doc.rect(15, y, 180, 20, "F")
  addField(doc, "Booking Reference", data.bookingRef, 20, y + 6)
  addField(doc, "Invoice No.", "INV-2024-SZ-04821", 100, y + 6)

  y += 28
  addField(doc, "Shipper", `${data.plant}`, 15, y)
  addField(doc, "Consignee", "Global Electronics Corp., Los Angeles", 100, y)

  y += 16

  // Items table
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Packing Details", 15, y)
  y += 6

  // Table header
  doc.setFillColor(30, 58, 95)
  doc.rect(15, y, 180, 8, "F")
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(8)
  doc.setFont("helvetica", "bold")
  const cols = [15, 30, 85, 115, 140, 165]
  doc.text("#", cols[0] + 2, y + 5.5)
  doc.text("Description", cols[1] + 2, y + 5.5)
  doc.text("Qty", cols[2] + 2, y + 5.5)
  doc.text("Net Wt (kg)", cols[3] + 2, y + 5.5)
  doc.text("Gross Wt (kg)", cols[4] + 2, y + 5.5)
  doc.text("Dims (cm)", cols[5] + 2, y + 5.5)

  y += 8

  const items = [
    ["1", "Laptop Motherboards (HS 8471.30)", "120 pcs", "4,200", "4,600", "60×40×30"],
    ["2", "LCD Display Panels (HS 8528.52)", "80 pcs", "3,400", "3,800", "55×35×25"],
    ["3", "SSD Storage Modules (HS 8471.70)", "200 pcs", "2,800", "3,000", "40×30×20"],
    ["4", "Battery Packs (HS 8507.60)", "160 pcs", "3,600", "3,900", "50×35×25"],
    ["5", "Keyboard Assemblies (HS 8471.60)", "120 pcs", "1,800", "2,000", "45×30×15"],
    ["6", "Power Adapters (HS 8504.40)", "240 pcs", "1,400", "1,700", "30×20×15"],
  ]

  items.forEach((item, idx) => {
    if (idx % 2 === 0) {
      doc.setFillColor(248, 249, 252)
      doc.rect(15, y, 180, 7, "F")
    }
    doc.setTextColor(50, 50, 50)
    doc.setFontSize(8)
    doc.setFont("helvetica", "normal")
    item.forEach((val, ci) => {
      doc.text(val, cols[ci] + 2, y + 5)
    })
    y += 7
  })

  // Totals
  y += 4
  doc.setDrawColor(30, 58, 95)
  doc.line(115, y, 195, y)
  y += 6
  doc.setFont("helvetica", "bold")
  doc.setFontSize(9)
  doc.setTextColor(30, 58, 95)
  doc.text("Total Packages:", 115, y)
  doc.text("240 cartons", 165, y)
  y += 6
  doc.text("Total Net Weight:", 115, y)
  doc.text("17,200 kg", 165, y)
  y += 6
  doc.text("Total Gross Weight:", 115, y)
  doc.text("18,400 kg", 165, y)

  y += 12
  addField(doc, "Container", data.containerType, 15, y)
  addField(doc, "Marks & Numbers", `MK: GEC-SZ-${data.bookingRef.slice(-5)}`, 100, y)

  addFooter(doc, data)
  const blob = doc.output("blob")
  window.open(URL.createObjectURL(blob), "_blank")
}

export function generateCustomsDeclaration(data: ShipmentData = DEFAULT_DATA): void {
  const doc = new jsPDF()
  addHeader(doc, "Customs Declaration (AES)")

  let y = 50

  doc.setFillColor(245, 247, 250)
  doc.rect(15, y, 180, 20, "F")
  addField(doc, "AES ITN", "X20240322-87234-001", 20, y + 6)
  addField(doc, "Booking Reference", data.bookingRef, 100, y + 6)

  y += 28
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Export Information", 15, y)
  y += 8

  addField(doc, "Exporter (USPPI)", `${data.plant} — Electronics Division`, 15, y)
  addField(doc, "EIN", "91-2345678", 140, y)
  y += 14
  addField(doc, "Ultimate Consignee", "Global Electronics Corp.", 15, y)
  addField(doc, "Country of Destination", "United States", 140, y)

  y += 16
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Commodity Details", 15, y)
  y += 6

  // HS code table
  doc.setFillColor(30, 58, 95)
  doc.rect(15, y, 180, 8, "F")
  doc.setTextColor(255)
  doc.setFontSize(8)
  doc.setFont("helvetica", "bold")
  doc.text("HS Code", 17, y + 5.5)
  doc.text("Description", 50, y + 5.5)
  doc.text("Value (USD)", 130, y + 5.5)
  doc.text("Origin", 170, y + 5.5)
  y += 8

  const commodities = [
    ["8471.30", "Laptop Motherboards", "$84,000", "China"],
    ["8528.52", "LCD Display Panels", "$62,400", "China"],
    ["8471.70", "SSD Storage Modules", "$56,000", "China"],
    ["8507.60", "Lithium Battery Packs", "$48,000", "China"],
    ["8471.60", "Keyboard Assemblies", "$14,400", "China"],
    ["8504.40", "Power Adapters", "$19,200", "China"],
  ]

  commodities.forEach((item, idx) => {
    if (idx % 2 === 0) {
      doc.setFillColor(248, 249, 252)
      doc.rect(15, y, 180, 7, "F")
    }
    doc.setTextColor(50, 50, 50)
    doc.setFontSize(8)
    doc.setFont("helvetica", "normal")
    doc.text(item[0], 17, y + 5)
    doc.text(item[1], 50, y + 5)
    doc.text(item[2], 130, y + 5)
    doc.text(item[3], 170, y + 5)
    y += 7
  })

  y += 6
  doc.setFont("helvetica", "bold")
  doc.setFontSize(9)
  doc.setTextColor(30, 58, 95)
  doc.text("Total Declared Value:", 100, y)
  doc.text("$284,000 USD", 155, y)

  y += 14
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Certifications", 15, y)
  y += 8
  doc.setTextColor(80, 80, 80)
  doc.setFontSize(9)
  doc.setFont("helvetica", "normal")
  doc.text("I declare that all statements made and all information contained herein are true and correct.", 15, y)
  y += 5
  doc.text("No dangerous goods or prohibited items are included in this shipment.", 15, y)
  y += 5
  doc.text("Export License: NLR (No License Required)", 15, y)

  y += 14
  addField(doc, "Date", new Date().toLocaleDateString("en", { year: "numeric", month: "long", day: "numeric" }), 15, y)
  addField(doc, "Authorized Signature", "________________________", 100, y)

  addFooter(doc, data)
  const blob = doc.output("blob")
  window.open(URL.createObjectURL(blob), "_blank")
}

// ── SAP Shipment Order ──────────────────────────────────────────────────
export function generateSAPShipmentOrder(orderRef: string): void {
  const doc = new jsPDF()
  addHeader(doc, `SAP Shipment Order — ${orderRef}`)
  let y = 50
  doc.setFillColor(245, 247, 250)
  doc.rect(15, y, 180, 20, "F")
  addField(doc, "SAP Order Reference", orderRef, 20, y + 6)
  addField(doc, "Created", new Date().toLocaleDateString("en", { year: "numeric", month: "short", day: "numeric" }), 120, y + 6)
  y += 28
  doc.setTextColor(30, 58, 95); doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.text("Shipment Details", 15, y); y += 8
  addField(doc, "Origin", "Shanghai, CN (CNSHA)", 15, y); addField(doc, "Destination", "Los Angeles, US (USLAX)", 100, y); y += 14
  addField(doc, "Mode", "Ocean FCL", 15, y); addField(doc, "Container Type", "40' High Cube", 100, y); y += 14
  addField(doc, "Target Ship Date", "Mar 15, 2025", 15, y); addField(doc, "Priority", "Standard", 100, y); y += 14
  addField(doc, "Plant", "Suzhou Plant — Electronics Division", 15, y); addField(doc, "Incoterm", "FOB Shanghai", 100, y)
  y += 20
  doc.setTextColor(30, 58, 95); doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.text("Material Description", 15, y); y += 8
  doc.setTextColor(50, 50, 50); doc.setFontSize(9); doc.setFont("helvetica", "normal")
  doc.text("Electronic components and laptop parts (HS 8471.30)", 15, y)
  doc.text("Gross Weight: 18,400 kg  |  240 cartons  |  Declared Value: $284,000", 15, y + 5)
  y += 18
  doc.setTextColor(30, 58, 95); doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.text("SAP Integration", 15, y); y += 8
  addField(doc, "SAP TM Order", orderRef, 15, y); addField(doc, "SAP ERP Sales Order", `SO-${orderRef.slice(-5)}-001`, 100, y); y += 14
  addField(doc, "OTM Shipment", `OTM-${orderRef.slice(-5)}`, 15, y); addField(doc, "Status", "Pending Booking", 100, y)
  addFooter(doc, DEFAULT_DATA)
  window.open(URL.createObjectURL(doc.output("blob")), "_blank")
}

// ── Booking Confirmation ────────────────────────────────────────────────
export function generateBookingConfirmation(bookingRef: string): void {
  const doc = new jsPDF()
  addHeader(doc, `Booking Confirmation — ${bookingRef}`)
  let y = 50
  doc.setFillColor(245, 247, 250); doc.rect(15, y, 180, 20, "F")
  addField(doc, "Booking Reference", bookingRef, 20, y + 6); addField(doc, "Status", "Confirmed", 120, y + 6)
  y += 28
  doc.setTextColor(30, 58, 95); doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.text("Voyage Details", 15, y); y += 8
  addField(doc, "Carrier", "Maersk Line", 15, y); addField(doc, "Vessel / Voyage", "Maersk Elba / AE-1234", 100, y); y += 14
  addField(doc, "Port of Loading", "Shanghai, CN (CNSHA)", 15, y); addField(doc, "Port of Discharge", "Los Angeles, US (USLAX)", 100, y); y += 14
  addField(doc, "Sailing Date", "Mar 15, 2025", 15, y); addField(doc, "ETA", "Apr 02, 2025", 100, y); y += 14
  addField(doc, "Container", "40' High Cube", 15, y); addField(doc, "Rate", "$2,850 (Contract)", 100, y)
  y += 20
  doc.setTextColor(30, 58, 95); doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.text("Terminal Instructions", 15, y); y += 8
  doc.setTextColor(50, 50, 50); doc.setFontSize(9); doc.setFont("helvetica", "normal")
  doc.text("Terminal: Yangshan Deep Water Port, Gate 7", 15, y)
  doc.text("Cargo Cutoff: Mar 14, 2025 12:00 local time", 15, y + 5)
  doc.text("Documentation Cutoff: Mar 14, 2025 18:00 local time", 15, y + 10)
  doc.text("VGM Submission: Required before cargo cutoff", 15, y + 15)
  addFooter(doc, DEFAULT_DATA)
  window.open(URL.createObjectURL(doc.output("blob")), "_blank")
}

// ── Rejection Notice ────────────────────────────────────────────────────
export function generateRejectionNotice(bookingRef: string): void {
  const doc = new jsPDF()
  addHeader(doc, `Booking Rejection Notice — ${bookingRef}`)
  let y = 50
  doc.setFillColor(255, 245, 245); doc.rect(15, y, 180, 20, "F")
  addField(doc, "Booking Reference", bookingRef, 20, y + 6); addField(doc, "Status", "REJECTED", 120, y + 6)
  y += 28
  doc.setTextColor(30, 58, 95); doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.text("Rejection Details", 15, y); y += 8
  addField(doc, "Route", "Chennai (MAA) → Houston (IAH)", 15, y); addField(doc, "Requested Sailing", "Mar 16, 2025", 100, y); y += 14
  addField(doc, "Carrier", "Maersk Line", 15, y); addField(doc, "Reason", "Vessel fully allocated", 100, y)
  y += 20
  doc.setTextColor(30, 58, 95); doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.text("Alternative Options", 15, y); y += 8
  doc.setTextColor(50, 50, 50); doc.setFontSize(9); doc.setFont("helvetica", "normal")
  doc.text("1. Next available Maersk sailing: Mar 20, 2025 ($2,900)", 15, y)
  doc.text("2. MSC — Mar 17, 2025 ($3,100, 2-day faster transit)", 15, y + 5)
  doc.text("3. CMA-CGM — Mar 18, 2025 ($2,950, via Colombo transship)", 15, y + 10)
  y += 24
  doc.setFillColor(255, 245, 245); doc.rect(15, y, 180, 14, "F")
  doc.setTextColor(180, 40, 40); doc.setFontSize(9); doc.setFont("helvetica", "bold")
  doc.text("Impact: 4-day delay risk — production impact est. $45K/day (IAH Petrochem Hub)", 20, y + 9)
  addFooter(doc, DEFAULT_DATA)
  window.open(URL.createObjectURL(doc.output("blob")), "_blank")
}

// ── Rate Advisory ───────────────────────────────────────────────────────
export function generateRateAdvisory(lane: string): void {
  const doc = new jsPDF()
  const displayLane = lane.replace(/[_-]/g, " → ").replace(/→ →/g, "→")
  addHeader(doc, `Rate Advisory — ${displayLane}`)
  let y = 50
  doc.setFillColor(245, 247, 250); doc.rect(15, y, 180, 20, "F")
  addField(doc, "Trade Lane", displayLane, 20, y + 6); addField(doc, "Effective", "Mar 12, 2025", 120, y + 6)
  y += 28
  doc.setTextColor(30, 58, 95); doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.text("Updated Spot Rates", 15, y); y += 6
  doc.setFillColor(30, 58, 95); doc.rect(15, y, 180, 8, "F"); doc.setTextColor(255); doc.setFontSize(8); doc.setFont("helvetica", "bold")
  doc.text("Container Type", 17, y + 5.5); doc.text("Previous Rate", 80, y + 5.5); doc.text("New Rate", 120, y + 5.5); doc.text("Change", 160, y + 5.5); y += 8
  const rates = [["40' Reefer", "$3,400", "$3,800", "+11.8%"], ["40' High Cube", "$2,900", "$3,200", "+10.3%"], ["20' Standard", "$1,900", "$2,100", "+10.5%"]]
  rates.forEach((r, idx) => {
    if (idx % 2 === 0) { doc.setFillColor(248, 249, 252); doc.rect(15, y, 180, 7, "F") }
    doc.setTextColor(50); doc.setFontSize(8); doc.setFont("helvetica", "normal"); doc.text(r[0], 17, y + 5); doc.text(r[1], 80, y + 5)
    doc.setFont("helvetica", "bold"); doc.text(r[2], 120, y + 5); doc.setTextColor(180, 60, 40); doc.text(r[3], 160, y + 5); y += 7
  })
  y += 10; doc.setTextColor(80); doc.setFontSize(9); doc.setFont("helvetica", "normal")
  doc.text("Contract rates remain unchanged. Validity: until Mar 20, 2025.", 15, y)
  addFooter(doc, DEFAULT_DATA)
  window.open(URL.createObjectURL(doc.output("blob")), "_blank")
}

// ── Exception Report ────────────────────────────────────────────────────
export function generateExceptionReport(bookingRef: string): void {
  const doc = new jsPDF()
  addHeader(doc, `Exception Report — ${bookingRef}`)
  let y = 50
  doc.setFillColor(255, 250, 240); doc.rect(15, y, 180, 20, "F")
  addField(doc, "Booking Reference", bookingRef, 20, y + 6); addField(doc, "Severity", "HIGH", 120, y + 6)
  y += 28
  doc.setTextColor(30, 58, 95); doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.text("Exception Details", 15, y); y += 8
  addField(doc, "Type", "Booking Exception — Agent Escalation", 15, y); addField(doc, "Detected By", "Zero Touch Booking Agent", 100, y); y += 14
  addField(doc, "Timestamp", new Date().toLocaleString("en", { dateStyle: "medium", timeStyle: "short" }), 15, y); addField(doc, "Agent Confidence", "92%", 100, y)
  y += 20
  doc.setTextColor(30, 58, 95); doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.text("Description", 15, y); y += 7
  doc.setTextColor(50); doc.setFontSize(9); doc.setFont("helvetica", "normal")
  doc.text("The booking agent encountered an exception during automated processing.", 15, y)
  doc.text("This exception requires human review before the booking can proceed.", 15, y + 5)
  y += 18
  doc.setTextColor(30, 58, 95); doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.text("Recommended Actions", 15, y); y += 7
  doc.setTextColor(50); doc.setFontSize(9); doc.setFont("helvetica", "normal")
  doc.text("1. Review exception details in the Exception Workbench", 15, y)
  doc.text("2. Verify data accuracy with origin plant team", 15, y + 5)
  doc.text("3. Approve resolution or escalate to supply chain manager", 15, y + 10)
  y += 24
  doc.setTextColor(30, 58, 95); doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.text("AI Analysis Sources", 15, y); y += 7
  doc.setTextColor(80); doc.setFontSize(8); doc.setFont("helvetica", "normal")
  doc.text("SAP TM  |  OTM  |  Carrier Portal  |  Rate Management System  |  Historical Booking Data", 15, y)
  addFooter(doc, DEFAULT_DATA)
  window.open(URL.createObjectURL(doc.output("blob")), "_blank")
}

// ── EDI Status Report ───────────────────────────────────────────────────
export function generateEDIStatus(bookingRef: string): void {
  const doc = new jsPDF()
  addHeader(doc, `EDI Status Report — ${bookingRef}`)
  let y = 50
  doc.setFillColor(245, 247, 250); doc.rect(15, y, 180, 20, "F")
  addField(doc, "Booking Reference", bookingRef, 20, y + 6); addField(doc, "EDI Type", "315 — Booking Status", 120, y + 6)
  y += 28
  doc.setTextColor(30, 58, 95); doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.text("Transaction Details", 15, y); y += 8
  addField(doc, "Carrier", "Hapag-Lloyd", 15, y); addField(doc, "Direction", "Inbound", 100, y); y += 14
  addField(doc, "Status Code", "DR — Documents Received", 15, y); addField(doc, "Confirmation", "Pending", 100, y); y += 14
  addField(doc, "Received", new Date().toLocaleString("en", { dateStyle: "medium", timeStyle: "short" }), 15, y); addField(doc, "Gateway", "EDI Gateway — Auto-processed", 100, y)
  y += 20
  doc.setTextColor(30, 58, 95); doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.text("Raw EDI Message Excerpt", 15, y); y += 7
  doc.setFillColor(240, 240, 245); doc.rect(15, y, 180, 30, "F")
  doc.setTextColor(60); doc.setFontSize(7); doc.setFont("courier", "normal")
  doc.text("ISA*00*          *00*          *ZZ*HLAG           *ZZ*COMPANY        *", 18, y + 5)
  doc.text("GS*QO*HLAG*COMPANY*20250313*0520*1*X*004010", 18, y + 9)
  doc.text("ST*315*0001", 18, y + 13)
  doc.text(`B1*HLAG*${bookingRef}*20250313*DR`, 18, y + 17)
  doc.text("SE*4*0001", 18, y + 21)
  addFooter(doc, DEFAULT_DATA)
  window.open(URL.createObjectURL(doc.output("blob")), "_blank")
}

// ── Carrier Contract PDF ────────────────────────────────────────────────
export interface ContractPDFData {
  id: string; carrier: string; status: string; effectiveDate: string; expiryDate: string
  totalVolumeCommitted: number; totalVolumeUsed: number
  lanes: { lane: string; mode: string; contractRate: number; currentSpotRate: number; volumeCommitted: number; volumeUsed: number }[]
}

function buildContractPDF(data: ContractPDFData): jsPDF {
  const doc = new jsPDF()
  // Header
  doc.setFillColor(30, 58, 95); doc.rect(0, 0, 210, 28, "F")
  doc.setTextColor(255); doc.setFontSize(16); doc.setFont("helvetica", "bold")
  doc.text("Freight Carrier Service Agreement", 15, 13)
  doc.setFontSize(9); doc.setFont("helvetica", "normal")
  doc.text(`Contract ${data.id} — ${data.carrier}`, 15, 20)
  doc.text("CONFIDENTIAL", 175, 20)

  let y = 36
  // 1. Contract Summary
  doc.setTextColor(30, 58, 95); doc.setFontSize(12); doc.setFont("helvetica", "bold")
  doc.text("1. Contract Summary", 15, y); y += 8
  doc.setFillColor(245, 247, 250); doc.rect(15, y, 180, 28, "F")
  addField(doc, "Contract ID", data.id, 20, y + 6)
  addField(doc, "Carrier", data.carrier, 80, y + 6)
  addField(doc, "Status", data.status, 140, y + 6)
  addField(doc, "Effective Date", data.effectiveDate, 20, y + 18)
  addField(doc, "Expiry Date", data.expiryDate, 80, y + 18)
  addField(doc, "Volume Commitment", `${data.totalVolumeCommitted.toLocaleString()} TEU`, 140, y + 18)

  y += 36
  // 2. Lane Rate Schedule
  doc.setTextColor(30, 58, 95); doc.setFontSize(12); doc.setFont("helvetica", "bold")
  doc.text("2. Lane Rate Schedule", 15, y); y += 6
  doc.setFillColor(30, 58, 95); doc.rect(15, y, 180, 8, "F")
  doc.setTextColor(255); doc.setFontSize(8); doc.setFont("helvetica", "bold")
  doc.text("Lane", 17, y + 5.5); doc.text("Mode", 55, y + 5.5); doc.text("Contract Rate", 80, y + 5.5)
  doc.text("Spot Rate", 110, y + 5.5); doc.text("Vol. Committed", 140, y + 5.5); doc.text("Vol. Used", 172, y + 5.5)
  y += 8
  data.lanes.forEach((lane, idx) => {
    if (idx % 2 === 0) { doc.setFillColor(248, 249, 252); doc.rect(15, y, 180, 7, "F") }
    doc.setTextColor(50); doc.setFontSize(8); doc.setFont("helvetica", "normal")
    doc.text(lane.lane, 17, y + 5); doc.text(lane.mode, 55, y + 5)
    doc.text(`$${lane.contractRate.toLocaleString()}`, 80, y + 5); doc.text(`$${lane.currentSpotRate.toLocaleString()}`, 110, y + 5)
    doc.text(`${lane.volumeCommitted.toLocaleString()} TEU`, 140, y + 5); doc.text(`${lane.volumeUsed.toLocaleString()} TEU`, 172, y + 5)
    y += 7
  })

  y += 8
  // 3. SLA Terms
  doc.setTextColor(30, 58, 95); doc.setFontSize(12); doc.setFont("helvetica", "bold")
  doc.text("3. Service Level Agreement (SLA)", 15, y); y += 7
  doc.setTextColor(50); doc.setFontSize(9); doc.setFont("helvetica", "normal")
  ;["On-Time Delivery (OTD): Carrier shall achieve minimum 95% OTD across all contracted lanes.",
    "Spot Buy Ratio: Total spot market spend shall not exceed 6% of contracted volume value.",
    "Data Entry Compliance: All booking records updated within 24 hours of receipt.",
    "Critical Shipment SLA: Critical shipments processed within 4 hours of request.",
    "Contracted Lane Utilization: Minimum 92% of committed volume utilized annually.",
  ].forEach(t => { doc.text(`  •  ${t}`, 15, y); y += 5 })

  y += 6
  // 4. Payment Terms
  doc.setTextColor(30, 58, 95); doc.setFontSize(12); doc.setFont("helvetica", "bold")
  doc.text("4. Payment Terms", 15, y); y += 7
  doc.setTextColor(50); doc.setFontSize(9); doc.setFont("helvetica", "normal")
  doc.text("Net 30 days from date of invoice. Late payments subject to 1.5% monthly interest.", 18, y); y += 5
  doc.text("Volume-based rebate: 3% rebate on annual spend exceeding committed volume by 10%+.", 18, y)

  y += 12
  // 5. Signatures
  doc.setTextColor(30, 58, 95); doc.setFontSize(12); doc.setFont("helvetica", "bold")
  doc.text("5. Signatures", 15, y); y += 8
  addField(doc, "Shipper", "________________________", 15, y)
  addField(doc, "Carrier", "________________________", 110, y)
  y += 12
  addField(doc, "Date", new Date().toLocaleDateString("en", { year: "numeric", month: "long", day: "numeric" }), 15, y)

  // Footer
  doc.setDrawColor(200); doc.line(15, 270, 195, 270)
  doc.setTextColor(150); doc.setFontSize(7); doc.setFont("helvetica", "normal")
  doc.text(`Contract ${data.id} | ${data.carrier} | Generated by Zero Touch Booking Agent`, 15, 274)
  return doc
}

export function generateContractPDF(data: ContractPDFData): void {
  const doc = buildContractPDF(data)
  window.open(URL.createObjectURL(doc.output("blob")), "_blank")
}

export function downloadContractPDF(data: ContractPDFData): void {
  const doc = buildContractPDF(data)
  doc.save(`Contract_${data.id}_${data.carrier.replace(/\s+/g, "_")}.pdf`)
}
